name: Cloud PC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Update system
      run: |
        sudo apt update

    - name: Install desktop
      run: |
        sudo apt install -y xfce4 xfce4-goodies
        sudo apt install -y chromium-browser
        sudo apt install -y x11vnc xvfb
        sudo apt install -y pulseaudio alsa-utils
        sudo apt install -y git curl wget npm

    - name: Start virtual display
      run: |
        Xvfb :1 -screen 0 1280x720x16 &
        sleep 2

    - name: Start desktop session
      run: |
        export DISPLAY=:1
        startxfce4 &

    - name: Start VNC server
      run: |
        x11vnc -display :1 -nopw -forever -shared -rfbport 5900 &

    - name: Install noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        git clone https://github.com/novnc/websockify noVNC/utils/websockify

    - name: Start noVNC
      run: |
        cd noVNC
        ./utils/novnc_proxy --vnc localhost:5900 &

    - name: Create public link
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        ./cloudflared tunnel --url http://localhost:6080

    - name: Keep alive
      run: |
        sleep 21600
